"""add_normalized_phone_and_make_email_nullable

Revision ID: 16956ff01b82
Revises: 259048d23573
Create Date: 2026-04-06 15:53:46.049463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16956ff01b82'
down_revision: Union[str, Sequence[str], None] = '259048d23573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('candidate_phone_normalized', sa.String(length=50), nullable=True))
    op.alter_column('applications', 'candidate_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_applications_candidate_phone_normalized'), 'applications', ['candidate_phone_normalized'], unique=False)
    op.drop_column('interview_questions', 'correct_option')
    op.drop_column('interview_questions', 'question_options')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('question_options', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('interview_questions', sa.Column('correct_option', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_applications_candidate_phone_normalized'), table_name='applications')
    op.alter_column('applications', 'candidate_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('applications', 'candidate_phone_normalized')
    # ### end Alembic commands ###
