"""Initial PostgreSQL Schema

Revision ID: 259048d23573
Revises: 
Create Date: 2026-04-03 22:11:47.768023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259048d23573'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_stages_stage_name'), 'application_stages', ['stage_name'], unique=False)
    op.create_index(op.f('ix_application_stages_stage_status'), 'application_stages', ['stage_status'], unique=False)
    op.alter_column('applications', 'resume_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_applications_phone_hash'), table_name='applications')
    op.drop_index(op.f('uq_application_job_phone_hash'), table_name='applications')
    op.create_unique_constraint('uq_application_job_phone_hash', 'applications', ['job_id', 'candidate_phone_hash'])
    op.create_index(op.f('ix_applications_candidate_phone_hash'), 'applications', ['candidate_phone_hash'], unique=False)
    op.create_index('ix_applications_dashboard_filters', 'applications', ['job_id', 'status', 'applied_at'], unique=False)
    op.create_index(op.f('ix_applications_hr_id'), 'applications', ['hr_id'], unique=False)
    op.drop_constraint(op.f('applications_hr_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['hr_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_interview_issues_candidate_email'), 'interview_issues', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_interview_issues_created_at'), 'interview_issues', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_issues_issue_type'), 'interview_issues', ['issue_type'], unique=False)
    op.drop_column('interview_questions', 'question_options')
    op.drop_column('interview_questions', 'correct_option')
    op.create_index('ix_jobs_description', 'jobs', ['description'], unique=False)
    op.create_index('ix_jobs_domain', 'jobs', ['domain'], unique=False)
    op.create_index('ix_jobs_experience_level', 'jobs', ['experience_level'], unique=False)
    op.create_index('ix_jobs_location', 'jobs', ['location'], unique=False)
    op.create_index('ix_jobs_primary_evaluated_skills', 'jobs', ['primary_evaluated_skills'], unique=False)
    op.create_index('ix_jobs_title', 'jobs', ['title'], unique=False)
    op.create_index(op.f('ix_users_approval_status'), 'users', ['approval_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_approval_status'), table_name='users')
    op.drop_index('ix_jobs_title', table_name='jobs')
    op.drop_index('ix_jobs_primary_evaluated_skills', table_name='jobs')
    op.drop_index('ix_jobs_location', table_name='jobs')
    op.drop_index('ix_jobs_experience_level', table_name='jobs')
    op.drop_index('ix_jobs_domain', table_name='jobs')
    op.drop_index('ix_jobs_description', table_name='jobs')
    op.add_column('interview_questions', sa.Column('correct_option', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interview_questions', sa.Column('question_options', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_interview_issues_issue_type'), table_name='interview_issues')
    op.drop_index(op.f('ix_interview_issues_created_at'), table_name='interview_issues')
    op.drop_index(op.f('ix_interview_issues_candidate_email'), table_name='interview_issues')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_hr_id_fkey'), 'applications', 'users', ['hr_id'], ['id'])
    op.drop_index(op.f('ix_applications_hr_id'), table_name='applications')
    op.drop_index('ix_applications_dashboard_filters', table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_phone_hash'), table_name='applications')
    op.drop_constraint('uq_application_job_phone_hash', 'applications', type_='unique')
    op.create_index(op.f('uq_application_job_phone_hash'), 'applications', ['job_id', 'candidate_phone_hash'], unique=True)
    op.create_index(op.f('ix_applications_phone_hash'), 'applications', ['candidate_phone_hash'], unique=False)
    op.alter_column('applications', 'resume_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_application_stages_stage_status'), table_name='application_stages')
    op.drop_index(op.f('ix_application_stages_stage_name'), table_name='application_stages')
    # ### end Alembic commands ###
